# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacios',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('vac_fecha_ini', models.DateField(verbose_name='Fecha inicio')),
                ('vac_hora_ini', models.TimeField(verbose_name='Hora inicio')),
                ('vac_fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('vac_hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('vac_observacion', models.TextField(null=True, verbose_name='Observaci\xf3n')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
        ),
    ]
