# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datalogger', '0021_auto_20171018_1238'),
        ('estacion', '0007_auto_20170705_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('ins_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ins_fecha_ini', models.DateField(verbose_name='Fecha de inicio')),
                ('ins_fecha_fin', models.DateField(verbose_name='fecha de fin ')),
                ('ins_en_uso', models.BooleanField(default=True, verbose_name='En uso')),
                ('ins_observacion', models.CharField(max_length=500, verbose_name='Nombre')),
                ('dat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalogger.Datalogger', verbose_name='Datalogger')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
            options={
                'ordering': ('ins_id', 'est_id', 'dat_id'),
            },
        ),
    ]
