# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='ins_fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='ins_observacion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Observacion'),
        ),
    ]
