# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='var_codigo',
            field=models.CharField(max_length=6, verbose_name='C\xf3digo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_err',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_min',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Error m\xednimo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xednimo'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_sos',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sos'),
        ),
    ]
