# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={},
        ),
        migrations.AlterField(
            model_name='control',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n'),
        ),
    ]
