# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0002_auto_20170626_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='con_fecha_fin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='control',
            name='con_fecha_ini',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
        migrations.AlterField(
            model_name='control',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n'),
        ),
    ]
