# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0005_auto_20170629_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='var_err',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Error m\xednimo'),
        ),
    ]
