# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0006_auto_20170629_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='con_estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='control',
            name='con_fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
    ]
