# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0007_auto_20170703_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ('est_id', 'var_id')},
        ),
    ]
