# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0012_auto_20180131_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='sen_id',
        ),
    ]
