# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
        ('variable', '0013_remove_control_sen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='sen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.Sensor', verbose_name='Sensor'),
        ),
    ]
