# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0014_control_sen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='sen_id',
        ),
    ]
