# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacion',
            name='val_validado',
        ),
    ]
