# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0002_remove_validacion_val_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacion',
            name='val_validado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Validado'),
        ),
    ]
