# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0003_validacion_val_validado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validacion',
            options={'ordering': ('val_id', 'est_id', 'var_id')},
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_estado',
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_hora',
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_maximo',
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_minimo',
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_validado',
        ),
        migrations.RemoveField(
            model_name='validacion',
            name='val_valor',
        ),
        migrations.AddField(
            model_name='validacion',
            name='val_fre_reg',
            field=models.IntegerField(default=0, verbose_name='N\xfamero de Registros'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='val_num_dat',
            field=models.IntegerField(default=0, verbose_name='N\xfamero de Datos'),
        ),
        migrations.AddField(
            model_name='validacion',
            name='val_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Procentaje'),
        ),
    ]
