# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0008_auto_20180315_0933'),
        ('variable', '0002_auto_20180131_1951'),
        ('validacion', '0004_auto_20170831_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('reg_fecha', models.DateTimeField(verbose_name='Fecha')),
                ('reg_usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('reg_accion', models.CharField(max_length=200, verbose_name='Acci\xf3n')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
            options={
                'ordering': ('reg_fecha',),
            },
        ),
    ]
