# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0005_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='variable',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
