# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sen_nombre', models.CharField(choices=[('Term\xf3metro', 'Term\xf3metro'), ('Higr\xf3metro', 'Higr\xf3metro'), ('Pluvi\xf3grafo', 'Pluvi\xf3grafo'), ('Veleta', 'Veleta'), ('Anem\xf3metro', 'Anem\xf3metro'), ('Bar\xf3metro', 'Bar\xf3metro'), ('TDR', 'TDR'), ('Piran\xf3metro', 'Piran\xf3metro'), ('Term\xf3metro de agua', 'Term\xf3metro de agua'), ('Sensor de nivel', 'Sensor de nivel')], max_length=20, verbose_name='Nombre')),
                ('sen_modelo', models.CharField(max_length=20, null=True, verbose_name='Modelo')),
                ('sen_serial', models.CharField(max_length=20, null=True, verbose_name='Serial')),
                ('sen_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('mar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca')),
            ],
            options={
                'ordering': ('sen_nombre', 'sen_modelo', 'sen_serial'),
            },
        ),
    ]
