# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_codigo', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('est_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('est_tipo', models.CharField(choices=[('M', 'Meteorol\xf3gica'), ('P', 'Pluviom\xe9trica'), ('H', 'Hidrol\xf3gica')], max_length=25, verbose_name='Tipo')),
                ('est_estado', models.BooleanField(default=True)),
                ('est_provincia', models.CharField(max_length=50, null=True, verbose_name='Provincia')),
                ('est_latitud', models.CharField(max_length=12, null=True, verbose_name='Latitud')),
                ('est_longitud', models.CharField(max_length=12, null=True, verbose_name='Longitud')),
                ('est_altura', models.IntegerField(null=True, verbose_name='Altura')),
                ('est_ficha', models.FileField(upload_to='fichas/')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vacios',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('vac_fecha_ini', models.DateField()),
                ('vac_fecha_fin', models.DateField()),
                ('vac_observacion', models.TextField(null=True, verbose_name='Observacion')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estacion')),
            ],
        ),
    ]
