# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='est_altura',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(6000), django.core.validators.MinValueValidator(0)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_ficha',
            field=models.FileField(upload_to='documents/', verbose_name='Fichas'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_latitud',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='est_longitud',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Longitud'),
        ),
    ]
