# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0002_auto_20170626_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='reg_archivo',
            field=models.CharField(max_length=50, null=True, verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='reg_ubicacion',
            field=models.CharField(max_length=200, null=True, verbose_name='Ubicacion'),
        ),
    ]
