# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0004_auto_20170627_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacios',
            name='vac_fecha_fin',
            field=models.DateField(verbose_name='Fecha fin'),
        ),
        migrations.AlterField(
            model_name='vacios',
            name='vac_fecha_ini',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
    ]
