# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0005_auto_20170628_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='est_estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
