# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0006_auto_20170629_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacios',
            name='est_id',
        ),
        migrations.DeleteModel(
            name='Vacios',
        ),
    ]
