# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='est_id',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
