# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0008_auto_20180315_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ('est_id',)},
        ),
    ]
