# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='med_hora',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='med_validado',
        ),
        migrations.AddField(
            model_name='datos',
            name='mar_id',
            field=models.IntegerField(default=0, verbose_name='Marca Datalogger'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datos',
            name='med_fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
