# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('mar_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('mar_nombre', models.CharField(max_length=25, verbose_name='Marca')),
            ],
        ),
    ]
