# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formato', '0009_auto_20170705_1645'),
        ('estacion', '0007_auto_20170705_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('imp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('imp_fecha', models.DateField(null=True, verbose_name='Fecha')),
                ('imp_hora', models.TimeField(null=True, verbose_name='Hora')),
                ('imp_archivo', models.FileField(upload_to='archivos/%Y_%m_%d_%H_%M/', verbose_name='Archivo')),
                ('imp_sobreescribir', models.NullBooleanField(default=False, verbose_name='Sobreescribir')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
                ('for_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato')),
            ],
        ),
    ]
