# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacion',
            name='imp_sobreescribir',
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_archivo',
            field=models.CharField(max_length=100, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_hora',
            field=models.TimeField(default=b'00:00:00', verbose_name='Hora'),
        ),
    ]
