# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('importacion', '0002_auto_20170830_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='mar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Datalogger'),
        ),
    ]
