# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0005_auto_20180227_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importacion',
            name='imp_hora',
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='mar_id',
        ),
        migrations.AddField(
            model_name='importacion',
            name='imp_fecha_fin',
            field=models.DateTimeField(default=b'2018-02-27 16:32:58', verbose_name='Fecha Final'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='imp_fecha_ini',
            field=models.DateTimeField(default=b'2018-02-27 16:32:58', verbose_name='Fecha Inicial'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateTimeField(default=b'2018-02-27 16:32:58', verbose_name='Fecha'),
        ),
    ]
