# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0012_auto_20180315_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateTimeField(default=b'2018-03-15 10:15:06', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_fin',
            field=models.DateTimeField(default=b'2018-03-15 10:15:06', verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_ini',
            field=models.DateTimeField(default=b'2018-03-15 10:15:06', verbose_name='Fecha Inicial'),
        ),
    ]
