# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importacion', '0015_auto_20180315_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='log_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones/Anotaciones'),
        ),
        migrations.AddField(
            model_name='importacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_fin',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_ini',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicial'),
        ),
    ]
