# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0016_auto_20180315_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importacion',
            old_name='log_mensaje',
            new_name='imp_observacion',
        ),
    ]
