# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0017_auto_20180315_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='imp_observacion',
            field=models.TextField(blank=True, default='Carga de Datos', null=True, verbose_name='Observaciones/Anotaciones'),
        ),
    ]
