# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0019_auto_20180316_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_ini',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicial'),
        ),
    ]
