# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0020_auto_20180316_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='importacion',
            name='imp_fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Final'),
        ),
    ]
