# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variable', '0008_auto_20170705_1645'),
        ('estacion', '0007_auto_20170705_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('fre_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fre_fecha_ini', models.DateField(verbose_name='Fecha inicio')),
                ('fre_fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
                ('var_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable')),
            ],
        ),
    ]
