# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frecuencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frecuencia',
            name='fre_valor',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(0)], verbose_name='Frecuencia (min)'),
        ),
    ]
