# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frecuencia', '0002_frecuencia_fre_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuencia',
            name='fre_fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
    ]
