# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicion', '0009_auto_20180202_1135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMedicion',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('med_valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Valor')),
                ('med_maximo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='M\xe1ximo')),
                ('med_minimo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='M\xednimo')),
                ('log_fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('log_accion', models.CharField(max_length=200, verbose_name='Acci\xf3n')),
                ('log_mensaje', models.TextField(verbose_name='Mensaje')),
                ('medicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicion.Medicion', verbose_name='Medicion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ('log_fecha',),
            },
        ),
    ]
