# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('variable', '0002_auto_20180131_1951'),
        ('estacion', '0008_auto_20180315_0933'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmedicion',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n'),
        ),
        migrations.AddField(
            model_name='logmedicion',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger'),
        ),
        migrations.AddField(
            model_name='logmedicion',
            name='med_fecha',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='logmedicion',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='logmedicion',
            name='medicion',
            field=models.IntegerField(verbose_name='medicion'),
        ),
    ]
