# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0002_auto_20170628_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacion',
            name='med_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicion.Medicion', verbose_name='Medici\xf3n'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='val_fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='val_hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='val_maximo',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='val_mensaje',
            field=models.CharField(max_length=100, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='validacion',
            name='val_minimo',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='M\xednimo'),
        ),
    ]
