# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0003_auto_20170628_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='med_maximo',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='M\xe1ximo'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='med_minimo',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='M\xednimo'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='med_validado',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Validado'),
        ),
    ]
