# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0006_auto_20170710_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacion',
            name='med_id',
        ),
        migrations.DeleteModel(
            name='Validacion',
        ),
    ]
