# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicion', '0007_auto_20170802_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ('med_fecha', 'med_hora')},
        ),
    ]
