# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('medicion', '0008_auto_20170914_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ('med_fecha',)},
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='med_hora',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='med_validado',
        ),
        migrations.AddField(
            model_name='medicion',
            name='mar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca Datalogger'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='med_fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
