# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0001_initial'),
        ('datalogger', '0001_initial'),
        ('variable', '0001_initial'),
        ('formato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('aso_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('cla_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cla_valor', models.IntegerField(verbose_name='Valor de Clasificacion')),
                ('cla_maximo', models.IntegerField(verbose_name='Maximo Valor de Clasificacion')),
                ('cla_minimo', models.IntegerField(verbose_name='Minimo Valor de Clasificacion')),
            ],
        ),
        migrations.AddField(
            model_name='formato',
            name='dat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalogger.Datalogger', verbose_name='Datalogger'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='for_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='var_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variable.Variable', verbose_name='Variable'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='for_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Formato', verbose_name='Formato'),
        ),
    ]
