# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0003_remove_datalogger_dat_nombre'),
        ('formato', '0005_delimitador_del_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociacion',
            name='est_id',
        ),
        migrations.AddField(
            model_name='asociacion',
            name='dat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalogger.Datalogger', verbose_name='Datalogger'),
        ),
    ]
