# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0007_remove_formato_dat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='cla_maximo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Columna m\xe1ximo valor'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='cla_minimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Columna m\xednimo valor'),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='cla_valor',
            field=models.IntegerField(verbose_name='Columna valor'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_archivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo'),
        ),
    ]
