# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0009_auto_20170705_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delimitador',
            name='del_codigo',
        ),
        migrations.RemoveField(
            model_name='delimitador',
            name='del_valor',
        ),
        migrations.AddField(
            model_name='delimitador',
            name='del_caracter',
            field=models.CharField(default='m', max_length=5, verbose_name='Caracter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delimitador',
            name='del_nombre',
            field=models.CharField(default='m', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
