# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0010_auto_20170728_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='for_hora',
            field=models.CharField(max_length=12, verbose_name='Formato de hora'),
        ),
    ]
