# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0012_formato_dat_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formato',
            old_name='dat_marca',
            new_name='mar_id',
        ),
    ]
