# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0014_auto_20170822_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='for_fecha',
            field=models.CharField(choices=[('MM/DD/YYYY', '%m/%d/%y'), ('YYYY-MM-DD', '%y-%m-%d')], max_length=12, verbose_name='Formato de fecha'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_hora',
            field=models.CharField(choices=[('HH:MM:SS', '%I:%M:%S %p')], max_length=12, verbose_name='Formato de hora'),
        ),
    ]
