# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0015_auto_20170830_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asociacion',
            options={'ordering': ('aso_id',)},
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_fecha',
            field=models.CharField(choices=[('%m/%d/%y', 'MM/DD/YYYY'), ('%y-%m-%d', 'YYYY-MM-DD')], max_length=12, verbose_name='Formato de fecha'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_hora',
            field=models.CharField(choices=[('%I:%M:%S %p', 'HH:MM:SS')], max_length=12, verbose_name='Formato de hora'),
        ),
    ]
