# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0016_auto_20170831_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='for_hora',
            field=models.CharField(choices=[('%I:%M:%S %p', 'HH:MM:SS AM/PM')], max_length=12, verbose_name='Formato de hora'),
        ),
    ]
