# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0017_auto_20170914_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='for_fecha',
            field=models.CharField(choices=[('%m/%d/%Y', 'MM/DD/YY'), ('%Y-%m-%d', 'YYYY-MM-DD'), ('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%d-%b-%y', 'DD-BB-YY')], max_length=12, verbose_name='Formato de fecha'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_hora',
            field=models.CharField(choices=[('%I:%M:%S %p', 'HH:MM:SS AM/PM'), ('%H:%M:%S', 'HH:MM:SS 24H'), ('%H:%M', 'HH:MM 24H')], max_length=12, verbose_name='Formato de hora'),
        ),
    ]
