# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0018_auto_20180109_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaHora',
            fields=[
                ('fec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fec_formato', models.CharField(max_length=20, verbose_name='Formato')),
                ('fec_codigo', models.CharField(max_length=20, verbose_name='C\xf3digo')),
                ('fec_tipo', models.CharField(choices=[('fecha', 'fecha'), ('hora', 'hora')], max_length=10, verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_fecha',
            field=models.CharField(choices=[('%d/%m/%y', 'DD/MM/YY'), ('%m/%d/%y', 'MM/DD/YY'), ('%Y-%m-%d', 'YYYY-MM-DD'), ('%d/%m/%Y', 'DD/MM/YYYY'), ('%m/%d/%Y', 'MM/DD/YYYY'), ('%d-%b-%y', 'DD-BB-YY'), ('%Y-%d-%m', 'YYYY-DD-MM'), ('%d-%m-%Y', 'DD-MM-YYYY')], max_length=12, verbose_name='Formato de fecha'),
        ),
    ]
