# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0020_auto_20180126_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('fec_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('fec_formato', models.CharField(max_length=20, verbose_name='Formato')),
                ('fec_codigo', models.CharField(max_length=20, verbose_name='C\xf3digo')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('hor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('hor_formato', models.CharField(max_length=20, verbose_name='Formato')),
                ('hor_codigo', models.CharField(max_length=20, verbose_name='C\xf3digo')),
            ],
        ),
    ]
