# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0022_auto_20180126_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='for_fecha',
        ),
        migrations.RemoveField(
            model_name='formato',
            name='for_hora',
        ),
    ]
