# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0023_auto_20180126_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='formato',
            name='for_tipo',
            field=models.CharField(choices=[('automatico', 'autom\xe1tico'), ('convencional', 'convencional')], default='convencional', max_length=50, verbose_name='Tipo de Formato'),
            preserve_default=False,
        ),
    ]
