# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0024_formato_for_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato',
            name='for_num_col',
        ),
        migrations.AlterField(
            model_name='formato',
            name='ext_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Extension', verbose_name='Extensi\xf3n del Archivo'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='fec_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Fecha', verbose_name='Formato de Fecha'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_archivo',
            field=models.CharField(blank=True, help_text='Solo aplica para transmisi\xf3n autom\xe1tica', max_length=100, null=True, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='for_nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Formato'),
        ),
        migrations.AlterField(
            model_name='formato',
            name='hor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formato.Hora', verbose_name='Formato de Hora'),
        ),
    ]
