# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0025_auto_20180220_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='for_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formato.Formato', verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='var_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='variable.Variable', verbose_name='Variable'),
            preserve_default=False,
        ),
    ]
