# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0026_auto_20180220_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delimitador',
            name='del_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
