# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogger',
            fields=[
                ('dat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('dat_codigo', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('dat_nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('dat_marca', models.CharField(max_length=25, null=True, verbose_name='Marca')),
                ('dat_modelo', models.CharField(max_length=25, null=True, verbose_name='Modelo')),
                ('dat_serial', models.CharField(max_length=25, null=True, verbose_name='Serial')),
                ('dat_estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sen_codigo', models.CharField(max_length=10, verbose_name='C\xf3digo')),
                ('sen_nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('sen_marca', models.CharField(max_length=20, null=True, verbose_name='Marca')),
                ('sen_modelo', models.CharField(max_length=20, null=True, verbose_name='Modelo')),
                ('sen_serial', models.CharField(max_length=20, null=True, verbose_name='Serial')),
                ('sen_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('dat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datalogger.Datalogger', verbose_name='Datalogger')),
            ],
        ),
    ]
