# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0005_auto_20170628_1525'),
        ('datalogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n'),
        ),
    ]
