# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0003_remove_datalogger_dat_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sen_codigo',
        ),
    ]
