# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0006_auto_20170630_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('sen_nombre', 'sen_marca', 'sen_modelo', 'sen_serial')},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='dat_id',
        ),
    ]
