# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0007_auto_20170705_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sen_marca_aux',
            field=models.CharField(max_length=20, null=True, verbose_name='Marca Aux'),
        ),
    ]
