# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0008_sensor_sen_marca_aux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ('sen_nombre', 'sen_modelo', 'sen_serial')},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sen_marca',
        ),
    ]
