# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0011_remove_sensor_sen_marca_aux'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='dat_marca_aux',
            field=models.CharField(max_length=25, null=True, verbose_name='Marca'),
        ),
    ]
