# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0012_datalogger_dat_marca_aux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalogger',
            name='dat_marca',
        ),
    ]
