# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('datalogger', '0013_remove_datalogger_dat_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='dat_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.Marca', verbose_name='Marca'),
        ),
    ]
