# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0015_remove_datalogger_dat_marca_aux'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalogger',
            name='dat_marca_aux',
            field=models.IntegerField(null=True, verbose_name='Modelo'),
        ),
    ]
