# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0017_auto_20170822_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalogger',
            name='dat_marca_aux',
        ),
    ]
