# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0019_auto_20170822_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalogger',
            options={'ordering': ('dat_codigo',)},
        ),
    ]
