# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variable', '0001_initial'),
        ('datalogger', '0020_auto_20170831_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='mar_id',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
