# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaAire',
            fields=[
                ('tai_id', models.AutoField(primary_key=True, serialize=False)),
                ('tai_mes', models.IntegerField(verbose_name='Mes')),
                ('tai_maximo_abs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo Absoluto')),
                ('tai_maximo_dia', models.IntegerField(verbose_name='D\xeda')),
                ('tai_minimo_abs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xednimo Absoluto')),
                ('tai_minimo_dia', models.IntegerField(verbose_name='D\xeda')),
                ('tai_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo')),
                ('tai_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xednimo')),
                ('tai_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio')),
            ],
            options={
                'ordering': ('tai_mes',),
            },
        ),
    ]
