# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('anuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturaaire',
            name='est_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n'),
        ),
        migrations.AddField(
            model_name='temperaturaaire',
            name='tai_periodo',
            field=models.IntegerField(default=2000, verbose_name='A\xf1o'),
        ),
    ]
