# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('anuarios', '0002_auto_20170915_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precipitacion',
            fields=[
                ('pre_id', models.AutoField(primary_key=True, serialize=False)),
                ('pre_periodo', models.IntegerField(verbose_name='A\xf1o')),
                ('pre_mes', models.IntegerField(verbose_name='Mes')),
                ('pre_suma', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precipitaci\xf3n')),
                ('pre_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo en 24H')),
                ('pre_maximo_dia', models.IntegerField(verbose_name='D\xeda')),
                ('pre_dias', models.IntegerField(verbose_name='Total de d\xedas con precipitacion')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
        ),
    ]
