# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('anuarios', '0003_precipitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumedadAire',
            fields=[
                ('hai_id', models.AutoField(primary_key=True, serialize=False)),
                ('hai_periodo', models.IntegerField(default=2000, verbose_name='A\xf1o')),
                ('hai_mes', models.IntegerField(verbose_name='Mes')),
                ('hai_maximo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo Absoluto')),
                ('hai_maximo_dia', models.IntegerField(verbose_name='D\xeda')),
                ('hai_minimo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo Absoluto')),
                ('hai_minimo_dia', models.IntegerField(verbose_name='D\xeda')),
                ('hai_promedio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo Absoluto')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
        ),
    ]
