# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuarios', '0004_humedadaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humedadaire',
            options={'ordering': ('hai_mes',)},
        ),
    ]
