# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuarios', '0011_viento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionvelocidad',
            name='est_id',
        ),
        migrations.RemoveField(
            model_name='viento',
            name='est_id',
        ),
        migrations.DeleteModel(
            name='DireccionVelocidad',
        ),
        migrations.DeleteModel(
            name='Viento',
        ),
    ]
