# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('anuarios', '0012_auto_20180110_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viento',
            fields=[
                ('vie_id', models.AutoField(primary_key=True, serialize=False)),
                ('vie_periodo', models.IntegerField(default=2000, verbose_name='A\xf1o')),
                ('vie_mes', models.IntegerField(verbose_name='Mes')),
                ('vie_vel_N', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Norte')),
                ('vie_por_N', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Norte')),
                ('vie_vel_NE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Noreste')),
                ('vie_por_NE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Noreste')),
                ('vie_vel_E', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Este')),
                ('vie_por_E', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Este')),
                ('vie_vel_SE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Sureste')),
                ('vie_por_SE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Sureste')),
                ('vie_vel_S', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Sur')),
                ('vie_por_S', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Sur')),
                ('vie_vel_SO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Suroeste')),
                ('vie_por_SO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Suroeste')),
                ('vie_vel_O', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Oeste')),
                ('vie_por_O', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Porcentaje de velocidad(m/s) al Oeste')),
                ('vie_vel_NO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Promedio de Velocidad(m/s) al Noroeste')),
                ('vie_por_NO', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Noroeste')),
                ('vie_calma', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Calma')),
                ('vie_obs', models.IntegerField(default=2000, verbose_name='Numero de Observaciones')),
                ('vie_vel_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Velocidad Mayor m/s')),
                ('vie_vel_dir', models.CharField(max_length=2, verbose_name='Direcci\xf3n Velocidad Mayor')),
                ('vie_vel_med', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Velocidad Media Km/h')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
        ),
    ]
