# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacion', '0007_auto_20170705_1645'),
        ('anuarios', '0013_viento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiacionMaxima',
            fields=[
                ('rad_id', models.AutoField(primary_key=True, serialize=False)),
                ('rad_periodo', models.IntegerField(default=2000, verbose_name='A\xf1o')),
                ('rad_mes', models.IntegerField(verbose_name='Mes')),
                ('rad_5', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='5')),
                ('rad_6', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='6')),
                ('rad_7', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='7')),
                ('rad_8', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='8')),
                ('rad_9', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='9')),
                ('rad_10', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='10')),
                ('rad_11', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='11')),
                ('rad_12', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='12')),
                ('rad_13', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='13')),
                ('rad_14', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='14')),
                ('rad_15', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='15')),
                ('rad_16', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='16')),
                ('rad_17', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='17')),
                ('rad_18', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='18')),
                ('rad_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xe1ximo')),
                ('rad_hora', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hora')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='RadiacionMinima',
            fields=[
                ('rad_id', models.AutoField(primary_key=True, serialize=False)),
                ('rad_periodo', models.IntegerField(default=2000, verbose_name='A\xf1o')),
                ('rad_mes', models.IntegerField(verbose_name='Mes')),
                ('rad_5', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='5')),
                ('rad_6', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='6')),
                ('rad_7', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='7')),
                ('rad_8', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='8')),
                ('rad_9', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='9')),
                ('rad_10', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='10')),
                ('rad_11', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='11')),
                ('rad_12', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='12')),
                ('rad_13', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='13')),
                ('rad_14', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='14')),
                ('rad_15', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='15')),
                ('rad_16', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='16')),
                ('rad_17', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='17')),
                ('rad_18', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='18')),
                ('rad_max', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='M\xednima')),
                ('rad_hora', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Hora')),
                ('est_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacion.Estacion', verbose_name='Estaci\xf3n')),
            ],
        ),
    ]
